config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "shortened_urls#index", as: :shortened_urls
  get "/:short_url", to: "shortened_urls#show"
  get "shortened/:short_url", to: "shortened_urls#shortened", as: :shortened
  post "/shortened_urls/create"
  get "/shortened_urls/fetch_original_url"
  get "/showcase/all_stats", to: "shortened_urls#overall_stats", as: :showcase_all_stats
  get "/showcase/stats/:short_url", to: "shortened_urls#stats", as: :showcase_stats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shortened_url.rb
require "open-uri"
require "nokogiri"

class ShortenedUrl < ApplicationRecord
  has_many :user_stats, dependent: :destroy
  UNIQUE_URI_LENGTH = 15
  validates :target_url, presence: true, on: :create
  validates_format_of :target_url, with: URI.regexp, on: :create
  before_create :generate_short_url
  before_create :santize
  before_create :retrieve_title

  # Generates a unique short URL for the current ShortenedUrl instance.
  #
  # This method uses SecureRandom to generate a random alphanumeric string of
  # length UNIQUE_URI_LENGTH. It checks the database for an existing ShortenedUrl
  # with the same short URL and recursively calls itself if a duplicate is found.
  #
  # Parameters: None
  #
  # Returns: None
  def generate_short_url
    url = SecureRandom.alphanumeric(UNIQUE_URI_LENGTH)
    possible_duplicate_url = ShortenedUrl.where(short_url: url).any?
    # Small check to prevent generating a duplicate short URL
    # Possible bug if same url is entered multiple times (more times than I could count), unique url is not possible then, will be infinte loop
    if possible_duplicate_url
      self.generate_short_url
    else
      self.short_url = url
    end
  end

  # Finds a duplicate of the current ShortenedUrl instance.
  #
  # This method uses the `find_by_sanitize_url` method to find a ShortenedUrl
  # instance with the same sanitized URL as the current instance.
  #
  # @return [ShortenedUrl, nil] The found duplicate ShortenedUrl instance, or nil
  #   if no duplicate is found.
  def find_duplicate
    ShortenedUrl.find_by_sanitize_url(self.sanitize_url)
  end

  # Checks if the current ShortenedUrl instance has a new URL.
  #
  # Parameters: None
  #
  # Returns: True if the URL is new, False otherwise.
  def new_url?
    find_duplicate.nil?
  end

  # Sanitizes the target URL by removing unnecessary protocol and subdomain information.
  #
  # This method modifies the target_url attribute by stripping leading/trailing whitespace,
  # converting to lowercase, and removing 'http://' or 'www.' prefixes.
  #
  # Parameters: None
  #
  # Returns: None
  def santize
    self.target_url.strip!
    self.sanitize_url = self.target_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
    self.sanitize_url = "http://#{self.sanitize_url}"
  end

  def retrieve_title
    begin
      html = URI.open(self.sanitize_url)
      # Read the first 1024 bytes to find the title tag quickly
      fragment = Nokogiri::HTML::DocumentFragment.parse(html.read(1024))
      self.title = fragment.at_css("title")&.text || "No title found"
    rescue => e
      Rails.logger.error "Failed to retrieve title for #{self.sanitize_url}: #{e.message}"
      self.title = nil
    end
  end
end

app/models/user_stat.rb
class UserStat < ApplicationRecord
  belongs_to :shortened_url
  validates :origin_country, presence: true

  # Auto geocoding, getting lat lang coordinates for showcase on maps
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? and obj.address_changed? }

  def address
    [ origin_city, origin_country ].compact.join(", ")
  end

  def address_changed?
    origin_city_changed? || origin_country_changed?
  end

  def geocode
    Rails.logger.debug "Geocoding address: #{address}"
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :find_url, only: [ :show, :shortened, :stats ]

  def index
    @url = ShortenedUrl.new
  end

  def show
    if Rails.env.development? || Rails.env.test?
      city_data = "Kuala Lumpur"
      country_data = "Malaysia"
      timezone = "Malaysia/Kuala_Lumpur"
    else
      city_data = request.location.city
      country_data = request.location.country
      user_ip = request.location.ip
      timezone = Geocoder.search(user_ip).first.data["timezone"]
    end
    @user_data = UserStat.new
    @user_data.origin_city = city_data
    @user_data.origin_country = country_data
    @user_data.timezone = timezone
    if @url
      @user_data.shortened_url_id = @url.id
      @user_data.save
      redirect_to @url.sanitize_url, allow_other_host: true
    else
      flash[:error] = "URL not found"
      redirect_to root_path
    end
  end

  def create
    @url = ShortenedUrl.new
    @url.target_url = params[:target_url]
    @url.santize
    if @url.save
      redirect_to shortened_path(@url.short_url)
    else
      flash[:error] = "Something went wrong when shortening your URL! Please try again."
      render "index"
    end
  end

  def shortened
    host = request.host_with_port
    @target_url = @url.sanitize_url
    @short_url = host + "/" + @url.short_url
    @short_code = @url.short_url
    @title = @url.title
  end

  def fetch_original_url
    fetch_url = ShortenedUrl.find_by_short_url(params[:short_url])
    redirect_to fetch_url.sanitize_url, allow_other_host: true
  end

  def overall_stats
    @user_stats = ShortenedUrl.page(params[:page]).per(10)
    @clicks_by_country = UserStat.group(:origin_country).count
    @clicks_by_timezone = UserStat.group(:timezone).count
    @clicks_over_time = UserStat.group_by_day(:created_at).count
    render "all_stats"
  end

  def stats
    @user_stats = UserStat.where(shortened_url_id: @url.id)
    @url_title = @url.title
    @clicks_by_country = @user_stats.group(:origin_country).count
    @clicks_by_timezone = @user_stats.group(:timezone).count
    @clicks_over_time = @user_stats.group_by_day(:created_at).count
  end

  private
  def find_url
    @url = ShortenedUrl.find_by_short_url(params[:short_url])
  end

  def url_params
    params.require(:url).permit(:target_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Shortener" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortened_urls/all_stats.html.erb
<div class="container mx-auto h-screen">
    <header class="p-4 bg-gray-100 flex w-full items-center justify-between">
        <%= link_to shortened_urls_path, class: "text-gray-600 hover:text-gray-800 transition duration-300 ease-in-out" do %>
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
        <% end %>
        <h1 class="text-2xl font-bold mb-4">User Stats</h1>
        <a href="/admin" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
            Admin Page
        </a>
    </header>
    <main class="flex-grow flex flex-col justify-center items-center p-4">
        <h2 class="text-xl font-semibold mb-2 text-center">Detailed User Stats</h2>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-200">
            <thead class="bg-gray-100">
                <tr>
                <th class="py-2 px-4 border-b border-gray-200 text-center">ID</th>
                <th class="py-2 px-4 border-b border-gray-200 text-center">Original URL</th>
                <th class="py-2 px-4 border-b border-gray-200 text-center">Shortened code</th>
                </tr>
            </thead>
            <tbody>
                <% @user_stats.each do |user_stat| %>
                <tr class="hover:bg-gray-50 cursor-pointer" onclick="window.location.href='/showcase/stats/<%= user_stat.short_url %>'">
                    <td class="py-2 px-4 border-b border-gray-200 text-center"><%= user_stat.id %></td>
                    <td class="py-2 px-4 border-b border-gray-200 text-center"><%= user_stat.target_url %></td>
                    <td class="py-2 px-4 border-b border-gray-200 text-center"><%= user_stat.short_url %></td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
        <div class="mt-4 flex justify-center">
            <%= paginate @user_stats %>
        </div>
    
        <div class="container mx-auto p-4">
            <header class="text-center">
            <h1 class="text-2xl font-bold mb-4">User Stats</h1>
            </header>
    
            <div class="mb-8">
    
            <div class="bg-white p-4 rounded-lg shadow">
                <%= line_chart @clicks_over_time, xtitle: "Date", ytitle: "Clicks", title: "Clicks Over Time" %>
            </div>
            </div>
    
            <div class="flex flex-wrap -mx-2">
            <div class="w-full md:w-1/2 p-2">
                <div class="bg-white p-4 rounded-lg shadow">
                <%= pie_chart @clicks_by_country, title: "Clicks by Country" %>
                </div>
            </div>
            <div class="w-full md:w-1/2 p-2">
                <div class="bg-white p-4 rounded-lg shadow">
                <%= pie_chart @clicks_by_timezone, title: "Clicks by Timezone" %>
                </div>
            </div>
            </div>
        </div>
    </main>
</div>

app/views/shortened_urls/index.html.erb
<div class="flex flex-col h-screen">
  <header class="p-4 bg-gray-100 flex w-full items-center justify-between">
        <a href="/showcase/all_stats" class="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
            Statistics page
        </a>
        <a href="/admin" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
            Admin Page
        </a>
  </header>
  <main class="flex-grow flex flex-col justify-center items-center p-4">
    <h1 class="text-4xl font-bold text-gray-900 mb-8">URL Shortener</h1>
    
    <%= simple_form_for :shortened_url, url: shortened_urls_create_path, method: :post, html: { class: "w-full max-w-md" } do |f| %>
      <div class="relative">
        <%= f.input :target_url,
            label: false,
            placeholder: 'Place your URL here to be shortened!',
            input_html: {
              class: "w-full px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
              autocomplete: "off",
              name: "target_url"  # This ensures the parameter name matches your controller expectations
            } %>
        
        <button type="submit" class="absolute right-2 top-1/2 transform -translate-y-1/2 p-2 bg-blue-500 text-white rounded-full hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out active:scale-90">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-scissors" viewBox="0 0 16 16">
            <path d="M3.5 3.5c-.614-.884-.074-1.962.858-2.5L8 7.226 11.642 1c.932.538 1.472 1.616.858 2.5L8.81 8.61l1.556 2.661a2.5 2.5 0 1 1-.794.637L8 9.73l-1.572 2.177a2.5 2.5 0 1 1-.794-.637L7.19 8.61zm2.5 10a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0m7 0a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
          </svg>
        </button>
      </div>
    <% end %>

    <% if flash[:error] %>
      <div class="mt-4 text-red-500"><%= flash[:error] %></div>
    <% end %>

    <% if flash[:notice] %>
      <div class="mt-4 text-blue-500"><%= flash[:notice] %></div>
    <% end %>
  </main>
</div>

app/views/shortened_urls/shortened.html.erb
<div class="flex flex-col h-screen">
  <header class="p-4 bg-gray-100 flex w-full items-center justify-between">
    <%= link_to shortened_urls_path, class: "text-gray-600 hover:text-gray-800 transition duration-300 ease-in-out" do %>
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg>
    <% end %>
    <a href="/showcase/stats/<%=@short_code%>" class="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
            Statistics page
        </a>
    <a href="/admin" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
      Admin Page
    </a>
  </header>

  <main class="flex-grow flex flex-col justify-center items-center p-4">
    <div class="max-w-2xl w-full space-y-8">
      <div class="bg-green-100 rounded-lg p-6 text-center">
        <h2 class="text-xl font-semibold mb-2">Page Title</h2>
        <p class="text-2xl text-gray-800 break-all">
          <%= @title %>
        </p>
      </div>
      <div class="bg-gray-100 rounded-lg p-6 text-center">
        <h2 class="text-xl font-semibold mb-2">Original URL</h2>
        <a href="<%= @target_url %>" 
           class="text-2xl text-blue-600 hover:text-blue-800 break-all" 
           onclick="window.location.href='<%= @target_url %>';">
          <%= @target_url %>
        </a>
      </div>

      <div class="bg-blue-100 rounded-lg p-6 text-center">
        <h2 class="text-xl font-semibold mb-2">Shortened URL</h2>
        <% formatted_short_url = @short_url.start_with?('http://', 'https://') ? @short_url : "http://#{@short_url}" %>
        <a href="<%= formatted_short_url %>" 
           class="text-2xl text-blue-600 hover:text-blue-800 break-all" 
           onclick="window.location.href='<%= formatted_short_url %>';">
          <%= formatted_short_url %>
        </a>
      </div>
    </div>
  </main>
</div>

app/views/shortened_urls/stats.html.erb
<div class="container mx-auto h-screen">
    <header class="p-4 bg-gray-100 flex w-full items-center justify-between">
        <%= link_to showcase_all_stats_path, class: "text-gray-600 hover:text-gray-800 transition duration-300 ease-in-out" do %>
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
        <% end %>
        <h1 class="text-2xl font-bold mb-4">User Stats for <%= @url_title %></h1>
        <a href="/admin" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform duration-200 ease-in-out">
            Admin Page
        </a>
    </header>
    <main class=" p-4">

        <div class="mb-8">
            <div class="bg-white p-4 rounded-lg shadow">
            <%= line_chart @clicks_over_time, xtitle: "Date", ytitle: "Clicks", title: "Clicks Over Time" %>
            </div>
        </div>

        <div class="flex flex-wrap -mx-2">
            <div class="w-full md:w-1/2 p-2">
            <div class="bg-white p-4 rounded-lg shadow">
                <%= pie_chart @clicks_by_country, title: "Clicks by Country" %>
            </div>
            </div>
            <div class="w-full md:w-1/2 p-2">
            <div class="bg-white p-4 rounded-lg shadow">
                <%= pie_chart @clicks_by_timezone, title: "Clicks by Timezone" %>
            </div>
            </div>
        </div>
    </main>
</div>